### ISSUE TITLE
registerAll function

### ISSUE THREAD

**Issue by YoloSanta** [vaperion/blade#10]
title says it :)

**Comment by YoloSanta** [comment]
if not basically it registers all the commands in one line, ex; qLibs (FrozenCommandHandler.registerAll(this);)

 public static void registerAll(Plugin plugin) {
        registerPackage(plugin, plugin.getClass().getPackage().getName());
    }

**Comment by vaperion** [comment]
Added in [2.1.0](https://github.com/vaperion/blade/releases/tag/2.1.0).
