### ISSUE TITLE
Invisible command parameters

### ISSUE THREAD

**Issue by Memexurer** [vaperion/blade#16]
I want to create a command with an invisible sender parameter.
```java
@Command({"is home", "is tp"})
public void home(@Sender Player player, @Sender Island playerIsland) {
  player.teleport(playerIsland.getSpawnLocation());
  player.sendMessage("Teleported to the island home!");
}
```
Then i would create a binding for playerIsland which checks if player has an island etc
And I want to make playerIsland parameter not visible in commands usage
Is it possible with current blade API?

**Comment by vaperion** [comment]
Currently, the usage generator is a mess. I am planning on rewriting it however I do not have much time right now. With the current API, you can't hide parameters, you can only append a custom message to the end. If you want to, you can make a pull request and I will merge it, if not I will get to this sooner or later.

**Comment by vaperion** [comment]
The new release [2.1.5](https://github.com/vaperion/blade/releases/tag/2.1.5) adds Command#usage, which can be used to set your own usage message, you can use this to hide the parameter.
