### ISSUE TITLE
Option to hide blade console warning

### ISSUE THREAD

**Issue by GamerRealm** [vaperion/blade#18]
Is there an option to hide the warning when a command takes a few milliseconds to execute?

```
[Blade] Command 'command' took 431 milliseconds to execute!
```

**Comment by vaperion** [comment]
Hello!

This warning is there to warn you about long command executions on the main thread, to suppress this warning you can either increase the threshold to a high value (which would basically disable the warning globally, which defeats the whole purpose of it) using `yourBladeInstance.executionTimeWarningThreshold(<big number here>)`, or by making the command async using `async = true` in your command annotation.
