### ISSUE TITLE
Registering a command out of the BladeBuilder

### ISSUE THREAD

**Issue by GamerRealm** [vaperion/blade#19]
Is it possible to register a command out of the blade builder?

**Comment by vaperion** [comment]
If you mean a static method then no, every blade instance has its own set of commands. If you want to register commands later on you can store your `Blade` instance in a variable, then access it later on, commands can be registered at any time.

Example:
```java
public class YourPlugin extends JavaPlugin {
    @Getter private static YourPlugin instance;
    @Getter private Blade blade;
    
    @Override
    public void onEnable() {
        instance = this;
        blade = Blade.of()
            ...
            .build();
    }
    
    public void someOtherMethod() {
        YourPlugin.getInstance().getBlade()
            .register(...)
            ...;
    }
}

**Comment by GamerRealm** [comment]
> If you mean a static method then no, every blade instance has its own set of commands. If you want to register commands later on you can store your `Blade` instance in a variable, then access it later on, commands can be registered at any time.
> 
> Example:
> 
> ```java
> public class YourPlugin extends JavaPlugin {
>     @Getter private static YourPlugin instance;
>     @Getter private Blade blade;
>     
>     @Override
>     public void onEnable() {
>         instance = this;
>         blade = Blade.of()
>             ...
>             .build();
>     }
>     
>     public void someOtherMethod() {
>         YourPlugin.getInstance().getBlade()
>             .register(...)
>             ...;
>     }
> }
> ```

Thats what I needed, thanks.
