### ISSUE TITLE
Console Command

### ISSUE THREAD

**Issue by GamerRealm** [vaperion/blade#21]
How would I make a command work for console and for a player?

For example a simple broadcast command like this:
```java
    @Command(value = {"broadcast"}, description = "Broadcast command.")
    @Permission(value = "core.broadcast")
    public static void onBroadcastCommand(@Sender Player player, @Combined String message) {
        Bukkit.broadcastMessage(CC.translate("&7[&4Broadcast&7] ") + CC.WHITE + message);
    }
    
```
How would I make it so that a player can use it and the console can use it?

**Comment by GitRowin** [comment]
Replace `@Sender Player player` with `@Sender CommandSender sender`.

**Comment by GamerRealm** [comment]
> Replace `@Sender Player player` with `@Sender CommandSender sender`.

Thanks.
