### ISSUE TITLE
Command Flags Issue

### ISSUE THREAD

**Issue by GamerRealm** [vaperion/blade#23]
So I have this ban command:
```java
    @Command(value = {"ban"}, async = true, description = "Ban Command.")
    @Permission(value = "core.staff")
    public static void onBanCommand(@Sender CommandSender sender, @Name("target") Player target, @Name("reason") @Optional @Combined String reason, @Name("-s") @Flag(value = 's', description = "Silent Ban") boolean silent) {
           //Do Ban Stuff
        }
```

But the issue is for some reason the flag (-s) is blue and is the first thing in the usage
![image](https://user-images.githubusercontent.com/42650369/158953891-103e69ae-bc15-4ff5-96b8-3c30096b8313.png)

Why is it like that and is it possible to change it?

**Comment by marvintheskid** [comment]
This is just how the default implementation of [UsageMessage](https://github.com/vaperion/blade/blob/master/src/main/java/me/vaperion/blade/command/impl/BukkitUsageMessage.java) generates the usage.

**Comment by GamerRealm** [comment]
> This is just how the default implementation of [UsageMessage](https://github.com/vaperion/blade/blob/master/src/main/java/me/vaperion/blade/command/impl/BukkitUsageMessage.java) generates the usage.
> 
> Edit: You can set the usage message for yourself in the Command annotation ([Command#usage](https://github.com/vaperion/blade/blob/master/src/main/java/me/vaperion/blade/annotation/Command.java#L45))

Thanks
