### ISSUE TITLE
Ghost Commands still being registered

### ISSUE THREAD

**Issue by Escapies** [vaperion/blade#25]
Commands in a deleted class (ghost class) will still appear in the command help and act as normal commands but are non-existent, only fix I've made is completely refactoring the package the command is in but that's a shitty fix.

**Comment by Escapies** [comment]
Whenever I delete a class, the command still gets registered and performs exactly like it should despite the code not even existing.

**Comment by vaperion** [comment]
This issue is not related to blade, a library does not have the ability to register classes that don't exist. Check your build system, perform a clean build.
