### ISSUE TITLE
Unregister command suggestion

### ISSUE THREAD

**Issue by GamerRealm** [vaperion/blade#27]
Hey so the unregister command system is really helpful but I was wondering if it would be possible to like have the unregister system unregister a command by its value? Like for example I have this command:

```java
    @Command(value = {"day", "daytime"}, description = "Day Command.")
    public static void onDayCommand(@Sender Player player) {

        player.sendMessage("Time set to Day!");
    }
```

And I could do like blade.unregisterValueCommand("day"); which would then unregister that command and its aliases.
This would be very helpful as all my command classes contain multiple commands and I want to have the ability to unregister just 1 command instead of all the commands in that class.

**Comment by vaperion** [comment]
This has been implemented in the upcoming 3.0.0 version.
