### ISSUE TITLE
Way to grab command label from command with aliases

### ISSUE THREAD

**Issue by jstnf** [vaperion/blade#36]
Hello,

I am wondering if there is a method or argument to grab the exact command label the sender used when executing a command. I think this is especially useful for commands with aliases.

cheers~

**Comment by vaperion** [comment]
Hi, you are only able to do this currently with `Context` at this time.

Example:
```java
import me.vaperion.blade.context.Context;
...

public static void example(Context context) {
  String alias = context.alias();
  ...
}
```

The downside of this is that you need to parse all the arguments yourself. Adding some kind of provider is planned, though I'm not sure when it will be added.
